version: "3.7"
services:
  postgres:
    image: postgres:alpine3.20
    container_name: order-service-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "wb_orders"
      POSTGRES_USER: "wb"
      POSTGRES_PASSWORD: "wb"
      PGDATA: "/pgdata"
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: order_service
    restart: on-failure
    depends_on: 
      - postgres
    environment:
      APP_IP: "0.0.0.0"
      APP_PORT: "8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "wb_orders"
      POSTGRES_USER: "wb"
      POSTGRES_PASSWORD: "wb"
    ports:
      - "8080:8080"